### ISSUE TITLE
⤵️. Add Redirect from Hacktoberfest to Contribute

### ISSUE THREAD

**Issue by keithrfung** [microsoft/electionguard#111]
## Feature Request

Add redirect from `electionguard.vote/hacktoberfest` -> `electionguard.vote/contribute`

This includes adding the `redirects` package.
https://github.com/datarobot/mkdocs-redirects
https://squidfunk.github.io/mkdocs-material/deprecations/#redirect

- [ ] Install line in make file
`pip install mkdocs-redirects`

- [ ] Add redirect to mkdocs
Example: _May need changes_
```
plugins:
    - redirects:
        redirect_maps:
            'hacktoberfest.md': 'contribute/index.md'
```
